import java.awt.Color;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chat/jen
 */

public class Task extends javax.swing.JFrame {
   
    public Task() {
        
        initComponents();
        ConnectSQL();
        Fetch();
       setTitle("My Task");

        
    }

    /** Creates new form Task */   
    DefaultTableModel df;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void ConnectSQL() {
        
        try {
            System.err.println("CONECTINGGGGGGGGGG");
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/chatlene","root","");
            
    }   catch (SQLException ex) {
            Logger.getLogger(Task.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Task.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TaskField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DeadlineField = new javax.swing.JTextField();
        DeleteTaskBtn = new javax.swing.JButton();
        DescriptionField = new javax.swing.JTextField();
        AssigneeField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AddTaskBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        MarkAsDoneBtn = new javax.swing.JButton();
        MarkAsTodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Work Task Management");
        setBackground(new java.awt.Color(225, 138, 170));

        jPanel2.setBackground(new java.awt.Color(233, 229, 225));

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 13)); // NOI18N
        jLabel1.setText("Task Name");

        TaskField.setBackground(new java.awt.Color(242, 232, 200));
        TaskField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(212, 204, 196), 3, true));
        TaskField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Sitka Subheading", 1, 13)); // NOI18N
        jLabel8.setText("Due Date");

        DeadlineField.setBackground(new java.awt.Color(242, 232, 200));
        DeadlineField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(212, 204, 196), 3, true));
        DeadlineField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeadlineFieldActionPerformed(evt);
            }
        });

        DeleteTaskBtn.setBackground(new java.awt.Color(118, 102, 86));
        DeleteTaskBtn.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        DeleteTaskBtn.setForeground(new java.awt.Color(244, 242, 240));
        DeleteTaskBtn.setText("Delete Task");
        DeleteTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteTaskBtnActionPerformed(evt);
            }
        });

        DescriptionField.setBackground(new java.awt.Color(242, 232, 200));
        DescriptionField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(212, 204, 196), 3, true));
        DescriptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionFieldActionPerformed(evt);
            }
        });

        AssigneeField.setBackground(new java.awt.Color(242, 232, 200));
        AssigneeField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(212, 204, 196), 3, true));
        AssigneeField.setSelectionColor(new java.awt.Color(212, 204, 196));
        AssigneeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssigneeFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Sitka Subheading", 1, 13)); // NOI18N
        jLabel7.setText("Assignee");

        AddTaskBtn.setBackground(new java.awt.Color(118, 102, 86));
        AddTaskBtn.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        AddTaskBtn.setForeground(new java.awt.Color(244, 242, 240));
        AddTaskBtn.setText("Add Task");
        AddTaskBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(118, 102, 86), 3, true));
        AddTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Sitka Subheading", 1, 13)); // NOI18N
        jLabel9.setText("Description");

        MarkAsDoneBtn.setBackground(new java.awt.Color(118, 102, 86));
        MarkAsDoneBtn.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        MarkAsDoneBtn.setForeground(new java.awt.Color(244, 242, 240));
        MarkAsDoneBtn.setText("Mark as Done");
        MarkAsDoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarkAsDoneBtnActionPerformed(evt);
            }
        });

        MarkAsTodo.setBackground(new java.awt.Color(118, 102, 86));
        MarkAsTodo.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        MarkAsTodo.setForeground(new java.awt.Color(244, 242, 240));
        MarkAsTodo.setText("Mark as On-going");
        MarkAsTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarkAsTodoActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(242, 232, 200));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(118, 102, 86), 2, true));
        jScrollPane1.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N

        jTable1.setBackground(new java.awt.Color(242, 232, 200));
        jTable1.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(118, 102, 86));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Assignee", "Task Name", "Description", "Deadline", "Task Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(242, 232, 200));
        jTable1.setRowHeight(31);
        jTable1.setSelectionBackground(new java.awt.Color(232, 211, 183));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(TaskField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(DeadlineField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(AssigneeField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(AddTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeleteTaskBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MarkAsTodo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MarkAsDoneBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TaskField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AssigneeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)))
                    .addComponent(AddTaskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(DeleteTaskBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MarkAsTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeadlineField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(MarkAsDoneBtn)))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(164, 144, 124));

        jLabel5.setBackground(new java.awt.Color(255, 255, 102));
        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(244, 242, 240));
        jLabel5.setText("To-Do's");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3a.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TaskFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaskFieldActionPerformed

    private void AddTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskBtnActionPerformed
        ImageIcon errIcon = new ImageIcon("C:\\Users\\Mico M Dumalanta\\OneDrive\\Desktop\\error.png"); 
        try {
            
            pst = con.prepareStatement("INSERT INTO task_table (task_name,task_status,task_description,task_deadline,task_assignee) VALUES (?,?,?,?,?)");
           try{
                String task = TaskField.getText();
                String description = DescriptionField.getText();
                String deadline = DeadlineField.getText();
                String assignee = AssigneeField.getText();
                
                if(task.isEmpty() || description.isEmpty() || deadline.isEmpty() || assignee.isEmpty()){
                    throw new Exception(" ");
                }
                
                pst.setString(1, task);
                pst.setString(2, "On-going");
                pst.setString(3,description);
                pst.setString(4,deadline);
                pst.setString(5,assignee);
                pst.executeUpdate();
           }catch(Exception ey){
               JOptionPane.showMessageDialog(null, "Please fill out all the necessary fields", "Invalid Input", JOptionPane.ERROR_MESSAGE, errIcon);
           }
           
        } catch (SQLException ex) {
            Logger.getLogger(Task.class.getName()).log(Level.SEVERE, null, ex);
        }
        TaskField.setText("");
        DescriptionField.setText("");
        DeadlineField.setText("");
        AssigneeField.setText("");
        Fetch();
        
    }//GEN-LAST:event_AddTaskBtnActionPerformed

    private void DeleteTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteTaskBtnActionPerformed
        int[] x = jTable1.getSelectedRows();
        
        for (int i = 0 ; i < x.length ; i++){
            try {
                Object xz = df.getValueAt(x[i],0);
                pst = con.prepareStatement("DELETE FROM task_table WHERE id = ?");
               System.out.println(xz.toString());

                
                pst.setString(1, xz.toString());
                pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Task.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Fetch();
    }//GEN-LAST:event_DeleteTaskBtnActionPerformed

    private void MarkAsDoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarkAsDoneBtnActionPerformed
        // TODO add your handling code here:        int[] x = jTable1.getSelectedRows();
        int[] x = jTable1.getSelectedRows();
        for (int i = 0 ; i < x.length ; i++){
            try {
                Object xz = df.getValueAt(x[i],0);
                pst = con.prepareStatement("UPDATE task_table SET task_status = ? WHERE id = ?");
                pst.setString(1, "Done");                
                pst.setString(2, xz.toString());
                pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Task.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Fetch();
    }//GEN-LAST:event_MarkAsDoneBtnActionPerformed

    private void MarkAsTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarkAsTodoActionPerformed
       // TODO add your handling code here:        int[] x = jTable1.getSelectedRows();
        int[] x = jTable1.getSelectedRows();
        for (int i = 0 ; i < x.length ; i++){
            try {
                Object xz = df.getValueAt(x[i],0);
                pst = con.prepareStatement("UPDATE task_table SET task_status = ? WHERE id = ?");
                pst.setString(1, "On-going");                
                pst.setString(2, xz.toString());
                pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Task.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Fetch();        // TODO add your handling code here:
    }//GEN-LAST:event_MarkAsTodoActionPerformed

    private void DeadlineFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeadlineFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeadlineFieldActionPerformed

    private void DescriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionFieldActionPerformed

    private void AssigneeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssigneeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssigneeFieldActionPerformed
    
    private void Fetch(){
        try {
            int q;
            pst = con.prepareStatement("SELECT * FROM task_table");
            rs = pst.executeQuery();
            
            ResultSetMetaData rss = rs.getMetaData();
            q = rss.getColumnCount();
            
            df =(DefaultTableModel)jTable1.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector v2 = new Vector();
                for (int i = 1 ; i <= q ; i++){
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("task_assignee"));
                    v2.add(rs.getString("task_name"));
                    v2.add(rs.getString("task_description"));
                    v2.add(rs.getString("task_deadline"));
                    v2.add(rs.getString("task_status"));
                }
                df.addRow(v2);
            } 
                    } catch (SQLException ex) {
            Logger.getLogger(Task.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Task.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Task().setVisible(true);
            }
        });
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTaskBtn;
    private javax.swing.JTextField AssigneeField;
    private javax.swing.JTextField DeadlineField;
    private javax.swing.JButton DeleteTaskBtn;
    private javax.swing.JTextField DescriptionField;
    private javax.swing.JButton MarkAsDoneBtn;
    private javax.swing.JButton MarkAsTodo;
    private javax.swing.JTextField TaskField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
